# Generated by Django 3.2.4 on 2021-06-22 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210621_1759'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=200)),
                ('book_id', models.CharField(max_length=20, unique=True)),
                ('author', models.CharField(max_length=50)),
                ('date', models.DateField()),
            ],
        ),
    ]
