# Generated by Django 3.2.4 on 2021-06-22 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=200)),
                ('book_id', models.CharField(max_length=20, unique=True)),
                ('usn', models.CharField(max_length=15)),
                ('date', models.DateField()),
            ],
        ),
    ]
